### ISSUE TITLE
Lack of escaping in `controllers/uaa.go`

### ISSUE THREAD

**Issue by aeijdenberg** [18F/cg-dashboard#1225]
I was taking a quick look over parts of the codebase to determine where the UAA client credentials were being used, and noticed that `controllers/uaa.go` contains some instances of lack of escaping data from either user input, or proxied content that is unsafe.

While I couldn't see an immediate obvious vulnerability, the code does look brittle in places, so I thought it worth documenting what I noticed (this is not exhaustive):

1. Manually constructed JSON output responses ([link to source](https://github.com/18F/cg-dashboard/blob/master/controllers/uaa.go#L186)):

```golang
err = &UaaError{http.StatusInternalServerError,
    []byte("{\"status\": \"failure\", \"data\": \"" +
        "unable to create user in UAA database.\", \"proxy-data\": \"" +
        string(body) + "\"}")}
```

What happens if `body` contains an `"` or a new line?

2. Unescaped SCIM query input ([link to source](https://github.com/18F/cg-dashboard/blob/master/controllers/uaa.go#L278)):

```golang
filterQuery := fmt.Sprintf("email eq \"%s\"", email)
reqURL := fmt.Sprintf("/Users?filter=%s", url.QueryEscape(filterQuery))
```

While the second line correctly escapes `filterQuery` before it is sent to the __privileged__ proxy, the first doesn't, meaning that whoever controls the input could include inject their own SCIM filter language.

3. Closest to an exploit: The `/uaa/uaainfo` endpoint can be used to execute an arbitrary query against UAA, as the `uaa_guid` parameter is not escaped (or otherwise safely treated) before being concatenated to the URL passed to the UAA proxy ([link to source](https://dashboard.system.g.cld.gov.au/uaa/uaainfo?uaa_guid=../Groups)):

```golang
func (c *UAAContext) UaaInfo(rw web.ResponseWriter, req *web.Request) {
	guid := req.URL.Query().Get("uaa_guid")
	if len(guid) > 0 {
		reqURL := fmt.Sprintf("%s%s", "/Users/", guid)
		c.uaaProxy(rw, req.Request, reqURL, false)
	} else {
		rw.WriteHeader(http.StatusBadRequest)
		rw.Write([]byte("{\"status\": \"Bad request\", \"error_description\": \"Missing valid guid.\"}"))
	}
}
```

e.g. a GET request as an authenticated user to: <https://dashboard.example.com/uaa/uaainfo?uaa_guid=../Groups> will list Groups instead of information about a specific user. If this was using the privileged proxy, it would be a bigger problem (since it's unprivileged, the user could presumably just ran the same query directly against UAA, so no big deal).

**Comment by jcscottiii** [comment]
@aeijdenberg first off, thanks for taking a look at the code base! really appreciate another pair of eyes.

Regarding number 1: 

The details of `body` should be logged instead of passed to the frontend (especially since the doesn't consume them). Having a better logging system will work out this part (you know, has like the request id and all)

Regarding 2:
I think validating the input would be beneficial here (i.e. checking that the input is actually an e-mail).

Regarding 3:
Yeah since it's the unprivileged proxy, shouldn't matter privilege wise. But you bring up a good point in terms of validating the guid is actually a guid. Another takeaway from this is looking to refactor so a developer doesn't accidentally use the privileged proxy by just passing the wrong boolean.

We will look into all of these. Thank you again!!!
If there's anything I may have misinterpreted / missed, let me know! Also, keep the feedback coming!

**Comment by aeijdenberg** [comment]
@jcscottiii - I put together a PR to fix a lot of what I saw and linked that above. The PR doesn't change the behavior - rather should just make it more robust against the potential issues described.

We're considering using this codebase as a frontend to one of our CF environments (within cloud.gov.au). Are you open to taking PRs for cleanup, especially on the Go backend side?

**Comment by jcscottiii** [comment]
@aeijdenberg we are open to any and all PRs!
