### ISSUE TITLE
Can't build front end

### ISSUE THREAD

**Issue by pilootchoum** [18F/cg-dashboard#439]
Hi there,

Just followed the instructions, and everything was fine so far, until I tried to build the frontend part,

After doing the npm install which worked, I ca'nt get the npm run build to work,

below the stack trace of the problem I'm getting, could you help me with this?

`npm run build

> cg-deck@1.0.0 build /home/vagrant/cg-deck-ws/src/github.com/18F/cg-deck
> npm run clean && node_modules/webpack/bin/webpack.js

> cg-deck@1.0.0 clean /home/vagrant/cg-deck-ws/src/github.com/18F/cg-deck
> rm -rf ./static/assets/*

Hash: d37c005ccf8e04627bda
Version: webpack 1.13.1
Time: 1283ms
    Asset    Size  Chunks             Chunk Names
bundle.js  247 kB       0  [emitted]  main
   [0] multi main 40 bytes {0} [built] [1 error]
    + 291 hidden modules

ERROR in multi main
Module not found: Error: Cannot resolve module '${srcDir}/main.js' in /home/vagrant/cg-deck-ws/src/github.com/18F/cg-deck
 @ multi main
`

Regards,
Michael

**Comment by msecret** [comment]
Hi @pilootchoum thanks for checking out the code base and reporting this issue.

I haven't been able to reproduce the problem so have some other questions:
- What version of node are you using?
- What branch are you on? We just switched over our master branch to be our previous `staging-alpha`.
- Is there anything in the `static_src` folder? What happens when you `ls -al` in the repo directory?

**Comment by pilootchoum** [comment]
hi msecret,

Sorry about the time to answer,
It seems I had a problem with my version of node.

I'm facing another issue right now, but I got the code to build so far.
I'm with version 6.2.2 of node now.

Regards
