### ISSUE TITLE
Rename components for consistency

### ISSUE THREAD

**Issue by msecret** [18F/cg-dashboard#461]
In order for developers to more easily find parts of the application and name new components, the React components should be more consistently named.

Acceptance criteria:
- [ ] `app.jsx` should be renamed to something else (like `main.jsx`) and `app_page.jsx` should be named `app.jsx`.

**Comment by msecret** [comment]
Should we have a naming scheme for components that are full pages? Examples are users, marketplace, space, app_page?

**Comment by jeremiak** [comment]
Perhaps for full page components we can call them "containers"? The idea would be that anything named `something_container.jsx` could be assumed to use the other components to form full views?

I don't really like "page" because we might end up with a different configuration of the components in the UI and the resulting bits may or may not be individual pages.

Proposal: Name the following files from the current name on the left to the name on the right:
* `app.jsx` -> `main_container.jsx`
* `app_page.jsx` -> `app_container.jsx`
* `space.jsx` -> `space_container.jsx` (maybe? My thinking is that since the `space.jsx` component actually holds the three tabbed components, it should also be called a container)

**Comment by msecret** [comment]
I love it!
