### ISSUE TITLE
Turn off coveralls

### ISSUE THREAD

**Issue by jeremiak** [18F/cg-dashboard#506]
I'm not sure we're actively using the information provided by the coveralls bot, but it can really clog up an issue/PR thread.

Can we turn it off for now and turn it back on when we have a way to work the data into our workflow?

@msecret @jcscottiii

**Comment by msecret** [comment]
I'm fine with it

**Comment by msecret** [comment]
I'd be nice to have a tool that would check code coverage on PRs, not write an annoying github comment like coveralls, but would end up in the same place as circle checks.

Ideally, I'd like to be able to see a graph of coverage so we can look at it in a sprint retro to see how we're doing rather and additionally see how each of your PRs changes the overall coverage.

I think the JS code is more important right now because the go code is barely changing.

**Comment by msecret** [comment]
After some research, I think we should use istanbul with some es6 plugin to make it work with es6 and integrate that with codecov. That would get us all the way there.
