### ISSUE TITLE
Investigate how to get log and event data from logs.cloud.gov

### ISSUE THREAD

**Issue by jeremiak** [18F/cg-dashboard#541]
We want the activity log feature to be useful and therefore want to incorporate data from the application logs to provide requisite context for the debugging user. Right now, we need to better understand how the dashboard application might request log and event data from `logs.cloud.gov`.

Refs #515
Moved from 18F/cg-product#223

**Comment by jcscottiii** [comment]
https://logs.cloud.gov and it's plugin https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/blob/develop/src/kibana-cf_authentication/index.js are setup to as handling oauth authentication (via UAA) for multiple users directly using it.

There are two problems that arise when trying to make it the dashboard talk to it.

1. logs.cloud.gov manages sessions via cookies (specifically cookie named `uaa-auth`, which is not a standard cookie for UAA). This works for when people are currently accessing it via their own computers because each browser maintains the cookies for that user. As of right now, if the dashboard connects to logs.cloud.gov, it will be seen as a single user. This becomes a problem when multiple users are trying to view the logs through a single dashboard server. 
  - The backend of the dashboard would need to:
    - Keep track of the cookie for each session of the user. (could just store that cookie inside the session for the dashboard user right now)

2. Authenticating automatically
Upon hitting logs.cloud.gov as an unauthenticated user, you are redirected to login.cloud.gov if you don't have a valid access token cached in logs.cloud.gov from the UAA. This workflow is great for actual users. Now for the dashboard trying to authenticate, it becomes tricky. How do you get an access token for logs.cloud.gov, which has certain scopes, by using the access token for user the dashboard user, which has its own scopes (although, the scopes right now overlap as of now)
  - We need a way for an external client to send over some creds, this plugin checks if those creds are valid, and then give access.
  - We don't want to give the dashboard any privileges it shouldn't have to get access to logs.cloud.gov and we need to enforce that.

**Comment by suprenant** [comment]
Considering this done. We investigated this and found the information we needed
