### ISSUE TITLE
Dashboard URLs should be human-readable and reflect system hierarchy

### ISSUE THREAD

**Issue by thisisdano** [18F/cg-dashboard#555]
For instance, a dashboard url could look like: 
`https://dashboard.cloud.gov/organization/space/app/_overview` to see an app overview
`https://dashboard.cloud.gov/organization/marketplace` to go to an org's marketplace

**Comment by msecret** [comment]
So currently the urls use the type of thing followed by the id of the thing in this manner:

`dashboard.cloud.gov/organization/2jfsdlfj02ijf/spaces/xcvmnza13rg`
`dashboard.cloud.gov/organization/fdjskfaljbcv/marketplace`

Should it instead use the type of thing and the name of thing rather then ID?

`dashboard.cloud.gov/organization/cf/spaces/dashboard-staging`
`dashboard.cloud.gov/organization/fec/marketplace`

OR should it use just the names without the types

`dashboard.cloud.gov/cf/dashboard-staging`
`dashboard.cloud.gov/fec/marketplace`

**Comment by thisisdano** [comment]
The third option seems most obvious, guessable, and readable to me, but it's worth getting more information. And we'd need to think through the implications — say, if a space has multiple dashboard views (overview, settings, etc) would those terms be 'reserved':

`dashboard.cloud.gov/fec/marketplace/overview`
In this case, `overview` couldn't also be the name of an app...

or a reserved term could be preceded by an underscore:
`dashboard.cloud.gov/fec/marketplace/_overview`

Anyhow, a bit to chew on here...

**Comment by msecret** [comment]
To answer some questions:
- We currently can't keep certain names from being reserved because we'd have to program that into the CLI as well as the dashboard. Based on what I've seen, changing the CLI to do that is possible but pretty difficult.
- We could use the underscore although theres still not guarantee that a user wouldn't name something with an underscore, so it feels a little hacky and dangerous to me. 

What we should still find out:
- Can orgs, spaces or apps be named the same thing? I'm guessing not because the names are used extensively as IDs in the CLI.
- How large of a performance impact this will have? The CF API allows only fetching and manipulating the data through the guids, not the names. This means in order for the urls to work without IDs, every single page will have to make a large request to get all orgs, spaces, apps, search for the guid with the app name in the url, make the normal requests we're making now to get the data. This now all has to be done before we can even render anything. If a user has a lot of orgs/spaces, this could slow down the site by a lot, in the magnitude of seconds.

**Comment by thisisdano** [comment]
I think these are important considerations. There are a number of quirks and issues to think about here, but I feel that the end result is worth it. That said, it _is_ an assumption without a real sense of the lift/impact. I'm hoping we can figure it out.

**Comment by thisisdano** [comment]
Here's an article about using anchor (#) links as pages: https://www.smashingmagazine.com/2015/12/reimagining-single-page-applications-progressive-enhancement/
