### ISSUE TITLE
Conduct microcopy review for app settings

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#563]
As a user, I want to be able to clearly understand the functionality of the Application settings panel by being able to read clear and accurate copy.

Ref 18F/cg-design/issues/5

cc @vz3 

Acceptance criteria:
- [ ] Schedule microcopy review with Content Designer (i.e. @brittag)
- [ ] Review a document with changes recommended from the microcopy review

**Comment by suprenant** [comment]
Holding on this issue for now. Will consider broader copy review as outcome of overall design audit.

**Comment by brittag** [comment]
Just something to consider:

If this comes up while I'm occupied by other work, rather than waiting for me (and getting blocked on that), this might be a good Writing Lab task (https://github.com/18F/writing-lab). :) The Writing Lab can be really helpful for short-timeframe discrete content review tasks like this (fewer than 10 hours).

**Comment by suprenant** [comment]
Thanks for the note, @brittag – makes sense and good to know.

cc @vz3
