### ISSUE TITLE
Bring in Cloud Foundry docs to Cloud.gov

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#583]
As a user, I can see documentation about the Cloud.gov platform, including materials that are not unique to Cloud.gov (i.e. related to Cloud Foundry). 

Notes: 
- Users aren't associating Cloud Foundry with Cloud.gov
- We want to select and provide sections of Cloud Foundry documentation to integrate to Cloud.gov
 - For implementation, we discussed that upstream templatization has had mixed results. Also, for reference, UAA technical research took 2 people 2-3 days
 - 100 pages of content that don’t necessarily match a schema, written in Ruby/ERB. Would need 

Next step would be to review the Cloud Foundry docs with @mogul and/or @brittag to select what content we would want to include

Acceptance criteria:
- [ ] List of relevant Cloud Foundry documents selected for implantation
- [ ] Map of template variable to our platform needs 
- [ ] The selection of Cloud Foundry documents are integrated into Cloud.gov and display properly with correct information
- [ ] Cloud.gov search indexes the integrated documents

**Comment by suprenant** [comment]
This is kludgy, but I took this screen grab when we were talking. It sounds like we are generally interested in these areas but need to determine what subsections we want:
 - cf Command Line Interface
 - Administer Cloud Foundry and Users

![screen shot 2016-09-01 at 10 56 35 am](https://cloud.githubusercontent.com/assets/1452369/18373746/711747de-760c-11e6-94c1-34d7f4e8ba37.png)

**Comment by mogul** [comment]
I think the .erb templates are basically in Markdown already, but they need
to be processed in order to fill in variables with cloud.gov-specific stuff
(eg api.cloud.gov, docs.cloud.gov, dashboard.cloud.gov, login.cloud.gov,
etc.) Then the processed markdown just needs to be stuck in the right place
in our Hugo config before generating the site. So it's kind of a
pre-processing step for the build process.

These are all pretty good candidates for inclusion:

- Cloud Foundry CLI
- Develop and Manage Applications
- Buildpacks

I see just a few pages that we might want to filter out (eg the page on
service-keys, since none of our services offer that).

Also I see one page I'd want to pull in without the rest of its surrounding
section:

- Cloud Foundry Concepts / Orgs, Spaces, Roles, and Permissions

:point_up: this one is critical.

**Comment by brittag** [comment]
Ooh, would you be up for moving this issue to https://github.com/18F/cg-docs/issues instead of cg-dashboard? I suspect there may be people (such as cloud.gov users at 18F) who are watching the cg-docs repo (but not this repo) and may be interested in giving input there.

**Comment by mogul** [comment]
Yeah, it should have been there to begin with. Let me try ZenHub's "Move Issue" feature, which I suspect works... poorly.

**Comment by mogul** [comment]
Issue moved to [18F/cg-docs #403](https://github.com/18F/cg-docs/issues/403) via [**ZenHub**](https://www.zenhub.com/)
