### ISSUE TITLE
Design usage and limits

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#618]

**Comment by suprenant** [comment]
Per @thisisdano, thinking this is up next

**Comment by thisisdano** [comment]
Here's where we are for the panel — but I'd really like to re-think it.
InVision here: https://gsa.invisionapp.com/d/main#/console/8652272/185319403/preview

![usage and limits 2x](https://cloud.githubusercontent.com/assets/11464021/18844127/c7d65624-83d0-11e6-810c-7ad779e057eb.png)

**Comment by thisisdano** [comment]
I'm thinking we'll want a usage and limits view that serves as a kind of usage overview — at least until we develop something like usage graphs. I'm going to try and make it a 12c panel at the top of the details, like so:

![app-overview 2x](https://cloud.githubusercontent.com/assets/11464021/18877536/66ddcb74-8482-11e6-8ea5-8e63efcb5ac8.png)

At least until it seems like it doesn't work!

**Comment by thisisdano** [comment]
@mogul 
According to the docs (https://docs.cloud.gov/intro/pricing/quotas/), quotas limit the following:
- Application routes.
- Application memory.
- Service instances.
- Access to paid plans.

But also (https://docs.cloud.gov/apps/limits/) applications can be limited with Application Limits by:
- memory
- disk
- instances [scale, yes?]

1. Is this accurate? Complete?
2. Do we not limit disk at the org/space level? Or you _can_ set disk quota but it has no relevance to billing?
3. We aren't explicit in the docs that quotas can apply to both the org and space level, but we do support both org and space quotas, yes?
4. I don't know what `access to paid plans` means. Can you explain it?
5. Are there any other important considerations with quotas and usage we should be aware of as we re/design the interface?
6. Anything else I'm forgetting?

**Comment by suprenant** [comment]
@thisisdano looks like this is In Progress – moving it there

**Comment by thisisdano** [comment]
7. Why is scale an additional Application Limit if there are already limits for memory and disk? Why couldn't you have as much scale as fits within the memory and disk limits?

**Comment by mogul** [comment]
> According to the docs (https://docs.cloud.gov/intro/pricing/quotas/), quotas can limit the following:
> - Application routes.
> - Application memory.
> - Service instances.
> - Access to paid plans.

Correct. The canonical list of org quota attributes is here: https://docs.cloudfoundry.org/adminguide/quota-plans.html#attributes

We're not doing anything involving the `total_reserved_route_ports` attribute.

Space quotas can limit the same things, but are completely optional, in which case the budget left for a given space is whatever's left of the overall org quota once the other spaces' existing usage is accounted for.

> But also (https://docs.cloud.gov/apps/limits/) applications can be limited with Application Limits by:
> - memory
> - disk
> - instances [scale, yes?]

Yes, these are settings that can be applied per-app. The canonical set of stuff you can set on an app is here (name is the only required attribute):
https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#optional-attributes

The three you listed are the only three that I would say act as limits.

> 1. Is this accurate? Complete?

Per above, yes.

> 2. Do we not limit disk at the org/space level? Or you _can_ set disk quota but it has no relevance to billing?

Correct, we're not limiting disk explicitly with the org  quota. 

> 3. We aren't explicit in the docs that quotas can apply to both the org and space level, but we do support both org and space quotas, yes?

Yes. OrgManagers are able to create SpaceQuotas for spaces in their orgs. In practice, this is rarely used, but someone trying to strictly control costs could take advantage of it. (I don't think it's a big priority to support in the dashboard, if that helps.)

> 4. I don't know what `access to paid plans` means. Can you explain it?

Each service that's available in the marketplace offers a range of plans... For example, a database service might offer a free "shared" plan, where the performance is not assured, but the cost to provide it is so small that we just give it away free. Then there might be higher-level plans that involve dedicated resources and additional costs for us to provide them, which we'll pass on to the customer. These plans are "paid" plans... They're marked that way in the API, and we don't allow people to set up instances of paid plans until they've signed an IAA, so that we have a mechanism to pass the costs back on to them via their invoice. So spaces in sandbox orgs, which are freely given out, are set to "can't use paid plans" as a way to restrict them from soaking us for costs we can't recover. Orgs associated with one of our paid tiers are set to allow use of paid plans.

> 5. Are there any other important considerations with quotas and usage we should be aware of as we re/design the interface?

Random thoughts:

- In many case the quota for an attribute is "unlimited" so you need to be prepared to show nothing for that attribute or else explain that (eg disk quota per above).
- In some cases there's a default value that gets set if the user doesn't do something explicit. For example the app memory limit default is 1G.
- People seem to have a hard time understanding that they multiply their app's memory limit by the number of instances to calculate its footprint, rather than subdividing it. So in your line graph above, you might think about visualizing the total usage for an app as a series of dashes equal to the number of instances, for example.
- The point about preventing continuous deployment in your comp above is perhaps reaching too far in assuming people will be doing blue-green deployments. They can deploy a smaller app next to an existing one with a smaller limit that fits, for example. Users should just see that they can't deploy when the remaining memory is more than what's needed.

> 6. Anything else I'm forgetting?

Not that I can see, thanks for being thorough!

**Comment by mogul** [comment]
Per Slack answer: There's no reason. We don't need to think of or portray
"scale/instances" as a limit, because it's not.

**Comment by thisisdano** [comment]
OK, I've made a new pass at usage and limits:

- removed graphs from this view to focus on being very explicit about instance usage, scale, total usage (instance x scale), and remaining space
- usage also includes a callout to a 7-day max to try and convey past usage without the lift of a graph
- `Remaining` is the most flexible of the columns
 - if application limit then remaining in application limit
 - else if space quota then remaining in space quota
 - else if org quota then remaining in org quota
 - else default limit (1 GB) if none explicitly set
- If either the org or space quota remaining > 1GB, the limit would be 1GB per Bret's info above
- I'm working on the actions to modify scale and add/modify application limits — coming soon!

Invision: https://gsa.invisionapp.com/d/#/console/8652272/191691942/preview
Sketch: https://github.com/18F/cg-design/raw/master/Sketch/cg-atomic-bass.sketch

![app-overview 2x](https://cloud.githubusercontent.com/assets/11464021/18956146/33f79620-860f-11e6-8757-28ba4133de98.png)

**Comment by thisisdano** [comment]
Added a preliminary `set scale` flow to the invision: https://gsa.invisionapp.com/d/#/console/8652272/192771128/preview

Updated Sketch: https://github.com/18F/cg-design/raw/master/Sketch/cg-atomic-bass.sketch

**Comment by thisisdano** [comment]
As we add more elements, the data density is creating visual crosstalk — that is, it's harder to pick out the groupings at a glance. So, I'm working on tweaking the panels and background to increase panel distinction and coherence. Here's a look:

- - - 

![app-overview 2x](https://cloud.githubusercontent.com/assets/11464021/18967527/61d403a0-863a-11e6-87ee-30b6602e025f.png)

 - - -

Also at the invision here: https://gsa.invisionapp.com/d/#/console/8652272/191691942/preview

**Comment by thisisdano** [comment]
I've changed the arrangement of the panel to put scale at the end — this gives is better separation and makes its application to both disk and memory more clear.

[New sketch](https://github.com/18F/cg-design/raw/master/Sketch/cg-atomic-bass.sketch)
[New invision](https://gsa.invisionapp.com/d/#/console/8652272/192771128/preview)

- - -

![usage-and-limits--default 2x](https://cloud.githubusercontent.com/assets/11464021/18969745/4c0c0c30-8643-11e6-83f8-e3e5e96ad44e.png)

**Comment by thisisdano** [comment]
Note that this is a little incorrect. I'll fix based on what I just learned on our call.

**Comment by thisisdano** [comment]
Implication of our call is that app-level limits will be MUCH more important to billing in the future.

**Comment by thisisdano** [comment]
OK, working through this issue.

As I understand it, application limits and scale are the key to our eventual billing system, so I'd love to try and get this good, clear, and accurate.

I'm hopeful this is on the right track.

- changed layout to (I hope) more accurately reflect the reality of the usage and limits
 - App limits reflect default values here [note: IDK if there's a default application limit for disk]. (Obviously, this panel would show updated values if user changes limits.)
 - App limit is an allocation/reservation for the individual instance
 - Scale multiplies the limit/allocation/reservation
- Using the term `allocation` (`reservation` could also work) instead of limit to more accurately reflect what it is
- Used graphs to show this relationship more clearly
- Used 7-day sparkline to show usage trend
- Made a little pass at showing cost per application resource allocation. (Though I understand that this is a later phase — this is how I understand usage-based billing, BTW. Am I thinking about his correctly?)

I haven't re-built the `modify allocation` and `modify scale` action flows yet.

- - -

![app--default 2x](https://cloud.githubusercontent.com/assets/11464021/18998574/13d70634-86ee-11e6-8dbe-efc7ed72edaf.png)

- - -

![app-overview 2x](https://cloud.githubusercontent.com/assets/11464021/18998582/1f6e009c-86ee-11e6-9a78-fe03c97ad4ab.png)

- - -

[Updated Sketch file](https://github.com/18F/cg-design/raw/master/Sketch/cg-atomic-bass.sketch)
[Updated Invision](https://gsa.invisionapp.com/share/8X8RHAOKS#/191691942_App-Overview)

@vz3 @mogul @dlapiduz @suprenant

**Comment by mogul** [comment]
Random reactions; may need a followup conversation:

- It seems like any information about quota/limit (as opposed to allocation and usage) belongs in the bottom section, with the graphs, rather than under the totals at top-right.
- Cost information tied to allocation information is spot-on for where we're going! However I think it should also show up under the total allocation on the right (where quotas are now) for consistency.
- Now that I've seen what's in metric events captured in logs.cloud.gov (and used by Abacus) I'm still unclear on if we have the metric information needed to show the actual usage relative to the allocation. :( It seems like we _must_ have that data since [the statistics plugin](https://github.com/swisscom/cf-statistics-plugin) effectively shows what we're after, and it has no special access to do that.
- The graph for total allocation of memory/disk for N instances vs used-elsewhere vs total is really nice! I don't think "2x scale" belongs under there because it's obvious up above and also indicated by the two cross-hatched blocks in the "total allocation". Showing it again it makes me think it represents a different, unrelated value. My feeling is that the big "2x" should be the single numerical representation of the scale in the whole panel.
- I know that "Total allocation" means the total for the app's instances based on context/hierarchy, but I worry whether users will understand that it's different than the total for the space or org. You might redundantly call it "App allocation" to make the point, which I think re-emphasizes that an app is the sum of its instances.
- The numerical information about usage at upper-left seems redundant and out of place given the explicit sparkline and graph below which show the same information with additional context.
- The bar graphs for instance usage are pretty hard to understand... I don't know what the black/red colors/hatching represents. Is this intended to represent the instantaneous usage, updating live? If so then there should be one per instance (and probably the same for the sparklines). 
- I really like that I can tell at a glance that a mostly-green bar in memory usage is "plenty free with room to grow"; I just don't know how to characterize a mostly-black bar. But if I'm interpreting that correctly, the connotation of the color green is different relative to the total allocation bars, and between the memory and disk allocation...? It feels like green should represent available/free, black should be used/allocated, and grey should be unavailable (eg used elsewhere) consistently between all these bars.
- Overall layout suggestion: Remove the usage info at upper-left. Move the total allocation bars to the bottom of the upper section, and make them wider to make it clear they represent both the instance and total allocation relative to quotas. Put instance disk usage and instance memory usage graphs in the same row, which can then be replicated vertically for as many instances as there actually are. The net result would be that the top section is clearly just "allocation" and the bottom section is clearly just "usage".

I am probably missing a lot, too. Lemme know if you want to chat about it.

**Comment by thisisdano** [comment]
@mogul Thanks for taking the time to analyze this panel and collect your feedback. 

Forgive me if some/all of the following description is unnecessary or redundant. I'd avoided any description of the thought process in the initial post, partly to allow fresh, uninfluenced eyes.

So, I think the primary purpose of this is to convey two relationships (which are, themselves, related): **instance usage/ instance allocation** and **total (scaled) allocation / remaining space in a quota**. This is how I've attempted to arrange the panel and I think it's how we should evaluate its performance.

There are two primary actions related to usage at the space level — adjusting the instance allocation (the *application limit* in cf terms) and adjusting the scale. 

From left to right (LTR), the panel includes:
- **Instance usage**: is restricted by...
- **Instance allocation (modifiable)**: which, when multiplied by... 
- **Scale multiplier (modifiable)**: results in...
- **Total application allocation**

The top half of the panel uses the raw numbers to communicate how these actions are related, almost like an equation. The bottom half of the panel uses the same data but focusses on spatial/contextual relationships to communicate the same information graphically.

Together, the user would use this data to determine
- How the app is performing within instance allocation
- How the app could be scaled within quota limits

To this end, I've tried to include as much historical usage data as possible without overwhelming the panel. I'm showing one week of historical data here, but there may be a better interval. In the top half, I'm using an arrow to show how the current usage compares to the start of the interval, and note the max usage within the interval. Below, I'm showing a more detailed sparkline (without labelled units) to show the trend. The sparkline is bounded by minimum and maximum usage, and extends seven days back from the current time. Each vertical line would indicate the start of a new calendar day.

This historical usage is also shown on the instance usage bar chart to the right of the sparkline. The shaded portion of the graph indicates the minimum-maximum range within the interval. (I don't think this is immediately obvious, though.)

I'm trying to use color as simply as possible. 
- **green:** OK
- **red:** warning (>80% usage in the instance or < 1 degree of scale in quota)
- **black:** used
- **gray:** unavailable
- **blue:** actionable

In this panel, both red and blue refer to **availability**. So, the red text at the top would refer to the amount of space available in the allocation/quota. I'm treating red and green bars in the graphs similarly. (Note: in the sketch above, there's also a gold intermediate stage between green and red. 
I propose removing that step and going to a binary system. Also, I'm going to change the availability text in the top section to describe what's available, rather than what's used, for consistency.)

The **Total allocation** bar chart shows how scaled application allocation relates to overall usage in the application's nearest quota limit (if there's a space quota, the graph would show that, otherwise it displays the organization quota). 

My biggest open question with this graph is how to make it clear that it's showing the scaled allocation. I'd like it to show allocated space, but also indicate that the total allocation is built from a multiplier of instances. I've split the total allocated bar into multiple equally-sized blocks equivalent to the number of scaled instances. This is why I've repeated the scale information below the graph — as a way to reiterate this concept. I don't know if it's necessary, but I _do_ feel it's a concept that needs strengthening.

Additionally, the sketch above attempts to convey instance usage in the total allocation graph by coloring the allocation with its availability status color (OK status instances would be green blocks, warning status instances would be red). I further attempted to distinguish this instance status from the quota availability status by shading the instances. I now think that this is too much data to convey in this chart. The new sketch just makes the instance allocation block black.

I have a semi-strong preference to continue to display each current component of the numbers view at the top of the panel _and_ the graphical view at the bottom of the panel. The LTR "equation" at the top makes the relationship between the parts feel very clear to me and the graphical display validates and expands this expression of the model. I think the redundancy works to strengthen the signal of the total message, and provides coherent parallelism. I think this will be even more clear as I develop the actions of changing the scale and allocation variables. (I hope to be able to update the data and graphs in real time to show the impact of the variable change.)

So, actions are coming soon, and here's a new version based on my first read on this feedback. More to come, I'd imagine.

- - -

![app--default 2x](https://cloud.githubusercontent.com/assets/11464021/19048132/e5c30928-8959-11e6-9f04-aa10e745a4c2.png)

- - -

[Updated Sketch file](https://github.com/18F/cg-design/raw/master/Sketch/cg-atomic-bass.sketch)
[Updated Invision](https://gsa.invisionapp.com/share/8X8RHAOKS#/191691942_App-Overview)

**Comment by thisisdano** [comment]
@mogul I'm happy to discuss this more in person if you think it'd be helpful

**Comment by thisisdano** [comment]
A couple further thoughts:
- This panel assumes it is possible and acceptable to use a single instance as a proxy for _any_ instance. Is this a reasonable assumption? How might we better display instance health?
- The panel doesn't account for resources that might be pooled _between_ instances, like, potentially, database storage. What might fall into this category? Do we want to display it in this panel in some way?

**Comment by msecret** [comment]
I remember at the start of this we determined that it isn't trivial to get historical data at this time because we don't have easy access to the data that's in kibana. @mogul has this changed? If not, then the MVP for this shouldn't include any historical data like the spike charts.

I wanted to bring this up now just in case that changes the design.

**Comment by thisisdano** [comment]
It was hard for me to follow the kind of data we were seeing in our talk last week — it _looked_ like we were seeing rapidly updated usage data (like every minute or so) and _thought_ I'd heard mentioned that that data could be the source of a usage graph display. I guess that's the Kibana data — but I never really had a sense of where it was coming from, or how we'd get it. I guess it sucks to think that it's easily accessible to Kibana but not to the native dashboard.

As it affects the design, tho, I think it'd be easy (but a bummer) to leave it off.

**Comment by msecret** [comment]
From my understanding, that data is from kibana. It's definitely not impossible to pull that data into the dashboard, but it's also not trivial due to how the UAA permissions work. Essentially, kibana asks for more permissions then the dashboard, so we'd have to build something to request those extra permissions from the user. More information on that can be seen here: https://github.com/18F/cg-dashboard/issues/541

**Comment by thisisdano** [comment]
OK — here's how the `Modify resource allocations` and `Modify application scale` actions could work. Actually, they could work together both independently and together!

- - -

Starting with a 500 MB memory allocation @ 4x scale

![usage-and-limits--default 2x](https://cloud.githubusercontent.com/assets/11464021/19085958/195e9546-8a21-11e6-9bc2-ee07907d235e.png)

- - -

Select `Modify application scale` to reveal an editable field. Changing elements in the panel turn blue. Memory scale bars are the length of their proportion of available space w/in the quota. Note that the disk total allocation bar always consumes 50% of an unlimited quota.

![usage-and-limits--change-scale-1 2x](https://cloud.githubusercontent.com/assets/11464021/19085992/3c8d95c6-8a21-11e6-91c6-2fde9c078894.png)

- - -

Reducing the scale changes the data.

![usage-and-limits--change-scale-2 2x](https://cloud.githubusercontent.com/assets/11464021/19086122/c7b7d4fe-8a21-11e6-9265-7e50550ffdfc.png)

- - -

Increasing scale past the availability throws an error and makes the `OK` button inactive. Overflow is shown with a shaded area in the total allocation graph.

![usage-and-limits--change-scale-3 2x](https://cloud.githubusercontent.com/assets/11464021/19086186/fadf1ed2-8a21-11e6-8970-e3da81ea1305.png)

- - -

So, since we're trying to allocate too much, we could reduce the instance allocation. These two variable action could be open _simultaneously_ — and their values would affect the state of the panel interdependently.

Since the active state is still in error, neither action can be successfully `OK`d (but they can be cancelled). There is a units selector in the input — switching back and forth would convert the value.

Note that the allocation labels turn blue in the instance allocation graph.

![usage-and-limits--change-scale-4 2x](https://cloud.githubusercontent.com/assets/11464021/19086397/d5c1124e-8a22-11e6-8781-1b15a324a634.png)

- - -

Reducing our instance memory allocation affects the panel data. Note that the instance allocation graph has red availability because the total bar is now less than the weekly max instance usage.

![usage-and-limits--change-scale-5 2x](https://cloud.githubusercontent.com/assets/11464021/19086428/f09825e4-8a22-11e6-93e1-6f06336c4c97.png)

- - -

Reducing the instance allocation means we have room to grow in scale. The `Max scale` button would input the maximum amount you could scale give the resource allocation and quota limit.

![usage-and-limits--change-scale-6 2x](https://cloud.githubusercontent.com/assets/11464021/19086741/34d035a2-8a24-11e6-932b-c81f4aba7698.png)

- - -

We can `OK` scale....

![usage-and-limits--change-scale-7 2x](https://cloud.githubusercontent.com/assets/11464021/19086579/948aa1c2-8a23-11e6-84f3-b5a2f6826899.png)

- - -

...and resource allocation. 

We've just changed from 500MB RAM @ 4x to 200 MB RAM at 11x, staying within our usage quota. :tada:

![usage-and-limits--change-scale-8 2x](https://cloud.githubusercontent.com/assets/11464021/19086594/a6abb54e-8a23-11e6-961a-bbc097913373.png)

- - -

You can see this live in the [invision](https://gsa.invisionapp.com/share/8X8RHAOKS#/192771128_Usage-And-Limits--default).

[Updated Sketch file](https://github.com/18F/cg-design/raw/master/Sketch/cg-atomic-bass.sketch)

**Comment by thisisdano** [comment]
You could also have a "flash-fade" effect (yellow BG fading out) on changed elements once `OK`d to reinforce that they changed. We could apply this effect similarly to other action panels.

**Comment by thisisdano** [comment]
After conversation with @vz3 I've made a couple adjustments:
- went back to an explicit `warn` state color (gold) to keep the error indicator (red) consistent across the dashboard (however, I've left the _text_ red, at least for now, since black didn't seem right and gold does not have enough contrast for text)
- removed min-max range indicator from the instance usage graph, since didn't have a clear read and  wasn't a critical component

We're planning to test this panel with users asap, and want to validate the assumption that scale is an important variable, how often apps use multiple x scale, and if it deserves the prominence we're developing for it here

- - -
Updated:
[Invision](https://gsa.invisionapp.com/share/8X8RHAOKS#/192771128_Usage-And-Limits--default)
[Sketch](https://github.com/18F/cg-design/raw/master/Sketch/cg-atomic-bass.sketch)

**Comment by thisisdano** [comment]
I had a new idea for the min-max range indicator, so I reinstated it!

- - -

![usage-and-limits--default 2x](https://cloud.githubusercontent.com/assets/11464021/19092574/2ac8c642-8a3c-11e6-88a6-ce1f23b01e33.png)

**Comment by vz3** [comment]
I dig it. How about putting the circles next to the min/max values?

**Comment by thisisdano** [comment]
Thinkin' that too. That's on deck.

**Comment by thisisdano** [comment]
![usage-and-limits--default 2x](https://cloud.githubusercontent.com/assets/11464021/19114967/0eaa8a16-8ac5-11e6-914b-b9c842946b70.png)

**Comment by thisisdano** [comment]
Re-organized this panel a bit after talking it through with @mogul. (Bret, did you ever commit those comments you were keeping?)

- Now there's one action to edit both scale and allocation
- New treatment of scale column
- Later: may try to work up a way to see/expand multiple running instances
- Turned on hotspots in Invision :)

- - -

![screen shot 2016-10-06 at 9 33 40 am](https://cloud.githubusercontent.com/assets/11464021/19161279/043dbbdc-8ba8-11e6-8596-858c754bde24.png)

- - -

[Invision](https://gsa.invisionapp.com/share/838UY596S#/192771128_Usage-And-Limits--default)
[Updated Sketch]([Sketch](https://github.com/18F/cg-design/raw/master/Sketch/cg-atomic-bass.sketch)

**Comment by dlapiduz** [comment]
@thisisdano The "App Scale" label is a bit confusing for me... I read it a couple times already and I always get confused.

Would it be better to say "Number of instances"?

**Comment by thisisdano** [comment]
@dlapiduz is "scale" not a common shorthand for "number of instances"? I made that assumption based on conversations and competitive analysis, but I never really knew for sure...

**Comment by dlapiduz** [comment]
@thisisdano I am not sure if others handle it that way but the way that you "scale" things in CF is not just on instances so I think that is what gets me.

You can scale apps on memory, disk and number of instances.

**Comment by thisisdano** [comment]
@dlapiduz hmmm. So you would use "scale" also to mean "changing the application limit/allocation"?

**Comment by dlapiduz** [comment]
Yeah I think so

**Comment by thisisdano** [comment]
That's good to know — thanks!

**Comment by thisisdano** [comment]
Another interview is revealing the truth of Mr @dlapiduz 's comment! :)
Change coming soon!

**Comment by mogul** [comment]
Sorry, I never did commit them... Now I have to fire those neurons back up.

Dan:
> This panel assumes it is possible and acceptable to use a single instance as a proxy for any instance. Is this a reasonable assumption? How might we better display instance health?

We talked about the fact that it may not be easy to get a full min-max range or current-average of instance usage that reflects all the instances without some additional work to accumulate it all. If we're going to try to show that data more work may be needed. We talked about increments being deliverable without having the min-max and average data available initially.

We talked about the fact that per-instance stats are a distraction when thinking about usage and limits, but invaluable when diagnosing a problem. We talked about potentially showing a floating panel with per-instance details when hovering over the instance usage graphs, clickable to reach just the logs for that instance. That is another story altogether, one about making it easy for people to diagnose problems with specific instances, which I don't think we should worry about now... Let's try to just focus on kicking butt at this usage and limits workflow.

Marco:
> I remember at the start of this we determined that it isn't trivial to get historical data at this time because we don't have easy access to the data that's in kibana. @mogul has this changed? If not, then the MVP for this shouldn't include any historical data like the spike charts.
> From my understanding, that data is from kibana. It's definitely not impossible to pull that data into the dashboard, but it's also not trivial due to how the UAA permissions work. Essentially, kibana asks for more permissions then the dashboard, so we'd have to build something to request those extra permissions from the user. More information on that can be seen here: #541

The platform data that logs.cloud.gov is slurping up and that you see in Kibana is also available to the dashboard, but that's more for instantaneous, running updates like you see reflected in the animated GIF here: https://github.com/swisscom/cf-statistics-plugin

To show usage history going back, you need to access a store of those events somewhere. I don't know that Kibana is the right place to try to extract that; it might be possible+better to target the underlying ElasticSearch instance, but I don't know enough to say; @LinuxBozo or @jmcarp may know better. Even if you can access the data out, it's likely raw samples and would need processing to give you appropriate intervals. Dunno if that points you back at Kibana, or maybe warrants a special-purpose microservice that does only that. (The other alternative would be to double-down on getting Abacus going, which basically does that in order to generate billing info, and I think will give you accumulated stats for time intervals.)

Dan and I also talked about figuring out if changing instance limits results in a push, restage, or restart... If it's the former two, then we probably need to worry about a pending/wait state before allowing other changes, eg a disabled operation-in-progress state on the form.
