### ISSUE TITLE
Integrate compliance and landing pages results into Cloud.gov nav search

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#622]
Previously agreed to do this but will follow up after docs search is finished

Previous notes: 

docs.cloud.gov is priority
but we do want to include other things, sitewide

cg-landing would be involved in the search
Index of cloud.gov except for the logged in experience/dashboard

Noted by @brittag: 
We can do a ‘faceted’ search - http://search.digitalgov.gov/manual/collections.html - so we can have a search interface that allows people to put in one keyword and choose basically whether they want “search within the docs site” “search within the compliance docs” “search within the marketing docs”

So for now, I’m going to leave it configured to just search docs.cloud.gov and cloud.gov/updates/ - but this is good to know! In the future, when we have user docs / marketing docs / ops docs separated out into different sections, we can have them as different search facets

the wonderful thing is that we can test configuration updates _instantly_ since it’s just using Bing’s index

**Comment by suprenant** [comment]
^^ @vz3 @juliaelman for reference, here are a few loose notes from the last time a group of us talked about this work. Again, we don't need to pick it up now, but let's keep it in consideration for future sprints.

**Comment by brittag** [comment]
Currently our search box is configured to cover all of these, which includes the overview (marketing) info:

![screen shot 2016-11-28 at 12 30 49 pm](https://cloud.githubusercontent.com/assets/391313/20684820/8adb4636-b566-11e6-8069-c5b085b141cb.png)

Our search box still says simply "search documentation:

![screen shot 2016-11-28 at 12 33 13 pm](https://cloud.githubusercontent.com/assets/391313/20684884/d86e25b2-b566-11e6-9d8c-60a4394eba4a.png)

We should probably update that copy, but I'm not sure what to put there instead of "documentation".

**Comment by brittag** [comment]
Closing this since I wrote up the remaining sticky part at https://github.com/18F/cg-design/issues/26
