### ISSUE TITLE
Creating a new service instance doesn't seem to work

### ISSUE THREAD

**Issue by brittag** [18F/cg-dashboard#672]
Using the current Dashboard (https://dashboard.cloud.gov/), if I go to my `britta.gustafson` space in my `sandbox` org and try to create a free service instance (such as `shared-psql`), it doesn't seem to work for me.

Example steps: I go to the Marketplace for my org, click `create service instance` in the services list, fill out the form at the bottom of the page, click `create service instance`, and nothing seems to happen. (I don't get feedback about whether it worked.) If I go check my space's list of service instances, I don't see a new instance there.

Related issue about adding feedback when people click `create service instance`: https://github.com/18F/cg-dashboard/issues/457

**Comment by msecret** [comment]
This is due to the `<Action>` component re-using the `type` property that's passed to it for styling purposes. Before the `type` property was used directly like the `type` attribute in HTML, so the action on the create service instance form would be `type="submit"`. Now that it's not a submit type anymore, the click handler on the button doesn't function properly.

Solution:
The best solution is to change the `<Action>` component to not re-use the `type` property for styling, but use it as the traditional `type` attribute on the button element. Additionally, all react components should probably not re-use actually html attribute names for properties, but that's something I'd like to solve later.

**Comment by msecret** [comment]
```js

Action
+ purpose | colorStyle: one of 'cautious', 'warning', 'primary', 'secondary'... (or rename things like 'primary', 'secondary' to more purposeful names.
+ styleType: one of 'outline', 'outline-inverse', 'link'.
+ type: any string (or should we limit to known possible values in HTML as of now?)
+ style: any object
```

**Comment by msecret** [comment]
Another option is to simplify the interface for less options and hopefully more consistency. There would be one purpose field that would control the button styles itself:

```
Action
+ purpose: one of 'cautious-complete', 'cautious-try', 'warning-complete', 'safe-edit' ...
+ type: any string (or should we limit to known possible values in HTML as of now?)
+ style: any object
```

**Comment by msecret** [comment]
@thisisdano @vz3 it might be helpful to get your thoughts on how we should configure/style our buttons

**Comment by suprenant** [comment]
@thisisdano to review here and follow up.

**Comment by brittag** [comment]
This works now, thanks everyone! It's a bit confusing since it doesn't consistently give feedback (the form seems to either disappear after service creation, or to stay there after service creation), but the service is created! The feedback thing is filed separately at https://github.com/18F/cg-dashboard/issues/457 :)
