### ISSUE TITLE
Indicate app status

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#705]
In order for a developer to quickly know if their app is running correctly, the app page should show the app status.

Acceptance criteria:
- [x] There should be a label element next to the name of the app if the status is errored.

Design: https://gsa.invisionapp.com/d/main/#/console/8652272/191691942/preview

**Comment by suprenant** [comment]
Discussed this with @msecret. This is basically done, though it doesn't yet look like the design @thisisdano produced. We proposed finishing and shipping this as-is and possibly updating the design in a subsequent sprint.

**Comment by suprenant** [comment]
@thisisdano the Invision link here is dead. Can you please update so we can review and approve?

**Comment by thisisdano** [comment]
I think this issue is old enough that it predates the breadcrumb nav. Here's the most recent error state design:

- error notification appears next to actions in the space below the header
- error notification could get an icon
- [phase 2] error status apps could have text/indicators in the breadcrumb nav 

![screen shot 2016-12-21 at 2 31 49 pm](https://cloud.githubusercontent.com/assets/11464021/21408523/5fd26a88-c78a-11e6-81d3-33349f3532cc.png)

**Comment by adborden** [comment]
:+1: The older design is in place.
