### ISSUE TITLE
Research human-readable URLs 

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#711]
What we're after: 
 - We believe it is helpful for users to know where they are
 - However, URLs are currently long and hard to read
 - It is hard to get app ID just by looking at the address bar
 - It could be valuable to demonstrate entity relationships via a path metaphor
 - It could also be useful to use a human-readable URL as a navigation tool

For this issue, we would like to further explore:
 - Goals related to human-readable URLs
 - Surface and consider issues that may arise in implementing these
 - Consider a cost/benefit analysis
 - Address questions around performance (e.g. currently, fetch data based on the page ID users are on, and we would need to fetch information that can point names to ID. With this, we have concerns about what could displayed before that data is fetched)

Related: https://github.com/18F/cg-dashboard/issues/555

Acceptance criteria:
 - [x] Initial notes/recommendations logged
 - [ ] Technical evaluation considering implementation has been conducted with notes/recommendations available
 - [ ] Program-level feedback has been solicited
 - [ ] Document of recommendations or implementation issue is available

**Comment by thisisdano** [comment]
So, human-readable URLs are good for legibility, orientation, navigation, and clarity of the model. But they _may_ have a performance hit? And they may be complicated? What's the cost/benefit of this nice feature?

**Benefits**
- clear and legible
- it's a best practice
- it's an expected behavior
- it makes location clear
- it clarifies the hierarchy/model
- it mirrors the navigation

**Complications**
- What would the URL actually look like? would `dashboard.cloud.gov/org/space/app` be flexible enough?
- Does it require reserved names?
- What else might it complicate?

Let's move on to costs! And expand on benefits/complications, if necessary!

Calling on @msecret @adborden @vz3 @brittag

**Comment by brittag** [comment]
Yay! Since the benefits are covered above, a tiny bit of input on the "complications" side: I suspect that potential additional performance impacts are important to consider for the Dashboard, since it's currently an experience where people may see occasional "loading" indicators during ordinary use. Also I'm a big fan of proactively preventing broken links, but that seems covered above. :D

**Comment by msecret** [comment]
### Answers to complications
- I think it would have to use `org`, `space` and `app` as identifiers due to not being able to keep reserved names in an easy way. So it would be like `/org/{org-name}/space/{space-name}/app/{app-name}`.
- That above wouldn't require reserved names because there's specified places where the names go.
- If we wanted reserved names, that'd be a big complication, because we'd have to modify the CLI AND the dashboard to support that. The only other complication is the one we've already been talking about: what are the performance implications of doing this? We could spend about 1 day of dev time researching the requests and the time it woudl take to complete them to see that impact.

**Comment by thisisdano** [comment]
I don't think that a simple `org/space/app` model requires any reserved names, as long as apps and spaces already need to have unique names. Is this true?

**Comment by thisisdano** [comment]
...at least, unique names within the org (for a space) or space (for an app)

**Comment by adborden** [comment]
Quoting Marco Segreto (2016-11-17 12:32:13)
> ### Answers to complications
> - I think it would have to use `org`, `space` and `app` as identifiers due to not being able to keep reserved names in an easy way. So it would be like `/org/{org-name}/space/{space-name}/app/{app-name}`.
> - That above wouldn't require reserved names because there's specified places where the names go.
> - If we wanted reserved names, that'd be a big complication, because we'd have to modify the CLI AND the dashboard to support that. The only other complication is the one we've already been talking about: what are the performance implications of doing this? We could spend about 1 day of dev time researching the requests and the time it woudl take to complete them to see that impact.

+1 to spending a day to research the performance impact. Might also be
able to explore the need for reserved names in this time.

--
Aaron D Borden
Human and Hacker

**Comment by adborden** [comment]
For this story I'd like to also consider getting rid of the fragment in
the url. I assume there's no reason for that?

e.g `/#/org/` -> `/org`

But if that's the case, there are definitely a few reserved names.
Prefixing the app at `/app` would also work around this.


--
Aaron D Borden
Human and Hacker

**Comment by thisisdano** [comment]
Just to be as clear as possible, I think would could have a URL scheme that looks like 

`dashboard.cloud.gov/[orgName]/[spaceName]/[appName]`

without running into reserved names, assuming all spaces need to have unique names in their org, and apps need to have unique names in their space (which I think is the case). A sample url might look something like:

`dashboard.cloud.gov/epa-journeyman/dev/journeyman-dev`

We are planning to fold the Marketplace into a services panel on the space page, so we don't need to reserve a name for it. I could see it getting tricky if a) we ever have multiple pages for a view; or b) need to have standalone features like service pages or ... compliance viewer pages. But those things are far enough out that I don't know how to plan for them.

**Comment by thisisdano** [comment]
A bit more robust scheme could be something like 

`/[orgName]/[spaceName]/[kind]/[kindName]/[kindSubpage]`

since apps and services live at the space level. This could translate into:

`/epa-journeyman/dev/apps/journeyman-dev`
`/epa-journeyman/dev/apps/journeyman-dev/compliance`
`/epa-journeyman/dev/services/jman-redis-instanceName`

This would also not require reserving names.

**Comment by thisisdano** [comment]
I would prefer not to have something like 

`dashboard.cloud.gov/orgs/[orgName]/spaces/[spaceName]/[kind]/[kindName]`

Even though its more robust, it's pretty cumbersome.

**Comment by thisisdano** [comment]
Github uses something like `https://github.com/thisisdano?tab=repositories` for multipage/subpage functionality, and that's not bad — as long as the parent page is a simple url.

**Comment by adborden** [comment]
Quoting Dan O. Williams (2016-11-23 10:10:48)
> A bit more robust scheme could be something like 
> 
> `/[orgName]/[spaceName]/[kind]/[kindName]/[kindSubpage]`
> 
> since apps and services live at the space level. This could translate into:
> 
> `/epa-journeyman/dev/apps/journeyman-dev`
> `/epa-journeyman/dev/apps/journeyman-dev/compliance`
> `/epa-journeyman/dev/services/jman-redis-instanceName`

I like this strategy. I believe your assumptions about org/space/app
uniqueness is correct.

--
Aaron D Borden
Human and Hacker

**Comment by msecret** [comment]
This is getting confusing, for the sake of this discussion, lets name the few URL schemes we're considering:

- segmented: `/orgs/[orgName]/spaces/[spaceName]/[kind]/[kindName]`
- partially-segmented: `/[orgName]/[spaceName]/[kind]/[kindName]`
- unsegmented: `/[orgName]/[spaceName]/[appName]`

I definitely think we should allow there to be more then one url for certain views. For instance, right now we have `users`, `apps`, `services` on the space level, as well as `marketplace` on the org level. While our design may be getting rid of these for now, we should allow them in any future URL scheme.

I think we could support the partially-segmented naming scheme in this way? But the scheme you proposed also assumes there will be no reserved names at the org level? So there wouldn't be something like:

`/[orgName]/services`.

So would that break if somebody has a space named "services"?

**Comment by thisisdano** [comment]
The p-s scheme would not include `orgName/services` or `[orgName]/[kind]` — it restricts segmentation to the space level. 
We intend to remove Marketplace from the top level (org) and move it to the space level. Users and Services are now just panels within views.

**Comment by msecret** [comment]
Ok that makes sense. What if down the road we need segmentation at the org level though? What if AUS wants to do so? Do you imagine any need to do so in the future?

**Comment by thisisdano** [comment]
That is the rub — I don't see any need to do it now or in the foreseeable future, but I can't say for certain we wouldn't.

**Comment by msecret** [comment]
@suprenant I'd be interested in getting your thoughts:

Should pick a URL scheme that's a better experience for our users at the risk that it wouldn't work accommodate  certain URLs in the future such as `org/services`?

**Comment by thisisdano** [comment]
My inclination is to go with something like the p-s scheme now (since it accomplishes our near and medium term goals) and approach undefined long-term issues as potentially solvable with reserved names — which isn't the right solution now, but may make more sense in the future.

In general, I am inclined not to over-engineer the scheme now for undefined future functionality.

**Comment by tessereth** [comment]
> What if AUS wants to do so?

We have no particular plans for features that would effect url choices. But weighing into this conversation now that I'm here, my understanding of the current question is:

* Is there anything below `/` other than organizations?
* Is there anything below `/[orgName]` other than spaces?

I can't think of anything that's globally scoped but domains are scoped to an organization as are org user roles. If you have plans to include those in the dashboard, you may need a more segmented path.

**Comment by thisisdano** [comment]
Hi @tessereth! I think you're parsing this Q pretty well. I may as well say that I think there are a couple spots where I think the dashboard will grow: 

1. Better control over apps (env vars, better analytics, github integration, pushing...)
2. App/Space compliance setup/monitoring
3. Fine-grained control over services
4. Org/space billing/invoices
5. User-specific information (full name, github, account, preferences, etc...)
6. User management

I think there are a few things in here that might cross over into the `/` or `/[orgName` domain — things that wouldn't be otherwise included in an org panel — like `dashboard.cloud.gov/users/[userName]` for seeing your (or someone else's) profile or or `dashboard.cloud.gov/[orgName]/billing` for accessing org billing. But I also think that the cases I imagine might better be served by some reserved names rather than a robust, flexible, fully segmented path. I imagine the bulk of our users will be working in orgs/apps/spaces and we should focus on a natural-language path for those common destinations and build ad-hoc common-sense additional namespaces that allow additional functionality. This might be a controversial position!

**Comment by tessereth** [comment]
Thinking about it some more, is it even possible to enforce a list of reserved names for orgs and spaces? I'm not aware of a way to do that at the cloud foundry level but then I haven't really looked. I don't know about you but we have a lot of different people who can create spaces at the moment and just asking them not to use certain names seems... questionable.

PS. I should point out that I don't have strong opinions on this. I'm just joining in the conversation because I can.

**Comment by msecret** [comment]
There's currently no way to enforce a list of reserved names at the Cloud Foundry level. Building a system to do so would not be trivial, and maybe not a great practice because we would have to fork CF functionality.

**Comment by thisisdano** [comment]
From my perspective, I'd like to think about what is the best experience for the user — what makes most intuitive sense, what clarifies the model, what expectations are, what feels right.

I think that p-s makes sense in (at least) the medium term, and that a system that reserves/forwards/whatever-engineering-solution a very limited subset of terms (like `/users`) is the best fit for my criteria. Perhaps forking CF is not a best practice, but we certainly have the ability to _change_ CF. I'm not saying this is the proper place for it, but as a large, important CF actor, we have something of an obligation to pursue user-centered modifications to CF — trivial or not. 

So — the critical Q for me is what is the best user-centered solution to this problem? Perhaps the futureproofing, engineering, implementation issues are too thorny to arrive at a consensus opinion right now — that's too bad, but to be expected perhaps. But the larger question is what can and should we do to be as clear as possible about what benefits the user. What do we test? What do we ask? 

@vz3 @brittag any suggestions for next steps?

**Comment by suprenant** [comment]
@vz3 to check in with folks at program level to get any feedback, outline next steps, and then we'll close this up.

**Comment by suprenant** [comment]
Part of this research is done, and we'd like to more clearly memorialize these learnings so they are available to team members in the future. We'd also like technical evaluation about the implications of implementation, which we're thinking will take about an day.

**Comment by suprenant** [comment]
@vz3 FYI, I tidied our acceptance criteria based on recent discussion here to hopefully make the path forward clear.

**Comment by adborden** [comment]
A lot of folks are using blue/green deployment via [autopilot](https://github.com/contraband/autopilot). In this case, a new app is created and the old app removed. I believe the guids change in that case, so it wouldn't be possible to bookmark an app since the URL would change on every deploy. Sticking to app names would work a little better in that case (though a failed deployment could mean the app exists under a different name e.g `app-name-venerable`).
