### ISSUE TITLE
Consider dashboard top nav

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#712]
In order to connect signed-in dashboard users to the necessary sections of cloud.gov, the primary ("top") nav of the dashboard should reflect those needs.

- [ ] Discuss needs of the signed-in user
- [ ] Determine what is "home" for that user
- [ ] Modify top-left link to clarify signed-in home
- [ ] Determine what navigation links need to be in the nav
- [ ] Determine what actions need to be in the nav
- [ ] Design distinction between destinations and actions
- [ ] Determine how all cloud.gov pages display signed-in status
- [ ] Disambiguate section naming
- [ ] Determine what nav appears on what section of cloud.gov
- [ ] Agree on plan of action with content design and Skyporter

Previous top nav issue:
https://github.com/18F/cg-dashboard/pull/674

Acceptance criteria:
- [x] Outline thinking
- [ ] Conduct technical review of possibilities of implementing this
- [ ] Possibly discuss with other folks in program (e.g. Britta, Bernd, James)

**Comment by suprenant** [comment]
@thisisdano to do some more grooming here

**Comment by thisisdano** [comment]
Here're my thoughts on this.

Let's look at how Heroku does this:

- signin brings you to dashboard.heroku.com
- heroku.com redirects to dashboard.heroku.com after signin
- marketing home accessed with heroku.com/home
- top-left target links to dashboard overview
- signed in topnav includes:
 - dashboard home link
 - search
 - docs (in a dropdown)
 - help (in a dropdown)
 - heroku-specific data types (in a dropdown)
 - user actions (signout, settings; in a dropdown)
- signed-in marketing home includes user actions (instead of signin button)
- signed-in marketing home includes dashboard access in a dropdown

In general: 
- all pages have a signed-in state
- the signed-in home is the dashboard
- documentation has its own subdomain/home
- help has its own subdomain/home

OK, then...
 - - -

The marketing page should be focussed on communicating the value of cloud.gov and driving aquisition of new customers.

Once that customer is on board, has an account, and is signed in, the site should be focussed on getting started, managing apps, and all the user needs outlined here: https://github.com/18F/cg-product/wiki/Users-and-needs

The top nav should be an expression of the top-level needs and tuned to the experience of using the platform.

I suggest we adopt a similar strategy to that of Heroku.
- all pages have a signed-in state
- the signed-in home is the dashboard
- documentation has its own subdomain/home
- actions should be differentiated from destinations

On the non–signed in marketing home nav:
- top-left target is marketing home
- About the Platform (currently Overview)
- Documentation
- Updates
- Contact
- [Sign in] button action
- [Search site/documentation] button action

Once signed in, cloud.gov forwards to dashboard and the top-left target is the dashboard.
The nav would be:
- top-left target is dashboard, displayed as [starbox]Dashboard
- Documentation
- Updates
- [maybe??] Help [where would this go?]
- [Sign out] button action
- [Search site/documentation] button action

In footer nav:
- Marketing home
- System status [with indicator]
- Contact
- Public domain stuff
- 18F link
- Github links

On non-dashboard signed-in pages, [signin] would be replaced with:
- Dashboard
- [Sign out] action button

**Comment by thisisdano** [comment]
Here's a look at how this might appear on the dashboard:

![screen shot 2016-11-22 at 11 48 05 am](https://cloud.githubusercontent.com/assets/11464021/20539382/a0cb5df8-b0a9-11e6-8167-42df51716a3a.png)

**Comment by brittag** [comment]
Possibly related issue that might be useful to consider here: https://github.com/18F/cg-site/issues/509 ("The dashboard link on the nav goes to east, confusing GovCloud users")

**Comment by suprenant** [comment]
Talking with @thisisdano now, feeling this is ready for review @vz3 @msecret

**Comment by suprenant** [comment]
@msecret to take a look here.

**Comment by thisisdano** [comment]
Thinking of pushing status up to the top nav in the dashboard
