### ISSUE TITLE
Get historical data for usage and limits (logs.cloud.gov)

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#713]
What we're after: 
 - Current UI has elements such as "-3MB from last week"
 - Need data for sparklines and graphs

To do this, we need:
 - Perform initial research to see if we can get data from logs.cloud.gov
 - Create code to pull data into dashboard

Notes:
 - Let's timebox this (few hours) and see what we can find

**Comment by suprenant** [comment]
@adborden and I talked through this a bit on Friday. Sounds uncertain if we'll be able to do much here now, but he's going to sync with @msecret to see what he thinks.

**Comment by adborden** [comment]
The main challenge here is being able to auth against the [kibana-cf_authentication](https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/blob/master/src/kibana-cf_authentication/index.js) plugin for logs.cloud.gov. The plugin uses an encrypted cookie, so we cannot proxy the dashboard request using the user's token we already have.

Based on the existing patterns, the most straight forward solution would be to add a Bearer token based auth to the kibana plugin, so we could pass an `Authorization` header just as we do for the other API requests.

However, I've spoken to @jmcarp a bit, and it might just make more sense to refer to a visualization in kibana rather than fetch and render the data ourselves.

Both of these solutions are cloud.gov specific, as this metric data would not necessarily be available to other Cloud Foundry instances so it's important that this feature be built with a fallback, perhaps as some kind of plugin.

**Comment by suprenant** [comment]
Considering this done – we generally know what's next here.
