### ISSUE TITLE
Test breadcrumb prototype with users

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#716]
What we're after: 
 - Conduct usability testing with 2-3 developers, 1-2 project managers
 - Keep lightweight given single pattern

Note:
 - Flagged this as dependent on https://github.com/18F/cg-dashboard/issues/718

Research docs:
 - https://docs.google.com/document/d/1oDudzqU9x3E4geLBgvnKAGUAit5Z4HOL6xZ2tJEOupo/edit#heading=h.36295sodksnj
 - https://docs.google.com/document/d/1P8s8CsSuQjhTQTcb-stTsViej73c390RM0xvSwapPVo
 - https://docs.google.com/document/d/1d66nxY3dAwWihZDOY2f4kniLRdjr0QtrwRbipxp7EiU

Acceptance criteria:
 - [x] Identify test subjects
 - [x] Develop scenario
 - [x] Schedule and conduct research
 - [ ] Write down and share out learnings and conclusions

**Comment by suprenant** [comment]
Considering holding on this until Overview page is ready.

**Comment by vz3** [comment]
Dependent on #722 #718

**Comment by thisisdano** [comment]
FYI, only the `epa-journayman`, `dev` and `journeyman-dev` items are active here. Page contents are also vv provisional. I think it'll be much more coherent as the pages come together.

**Comment by suprenant** [comment]
We're planning on moving forward with testing using the Invision prototypes.

**Comment by suprenant** [comment]
Noting that we're feeling the breadcrumb is now ready for testing, so this issue is not blocked.

**Comment by thisisdano** [comment]
Some preliminary findings (about other stuff than the breadcrumb)...

**Session 1**
- a little hesitation wrt breadcrumb: needing to click twice to nav to the previous view was not natural
- Breadcrumb does make logical sense/hierarchy and design decisions make sense

**Session 2**
- Contents needs labeling on the home panels
- Breadcrumb nav is working pretty well
- Status bars are not adding much value yet
- Icons grow in value with familiarity
- Docs links are important/expected (for roles particularly)
- Layout of roles could have semantic meaning: LTR could indicate lessening or heightening of role status
- Users are highly primed to find meaning in our layout/display choices — they want to make connections and learn how things connect/relate

**Session 3**
- Clickability of the primary nav in the breadcrumb is an issue
- Users use the contents panel for navigation
- Returning to home for org switching may not be too cumbersome
- Can we simplify the breadcrumb, reduce clicks?
- Lack of sidebar is not necessarily an issue (contents panel compensates), but breadcrumb should be more streamlined
- Findability of scrolling down page is a mild irritant — can we communicate page contents without requiring scroll? Leads user to think some contents panels are too long (roadblocking).
- Provisioning/Binding service instances flow is an important one — even if it happens infrequently
- User roles are mysterious

**Comment by thisisdano** [comment]
Overall design look-and-feel feedback is positive. 
A few flows and interactions to tighten/clarify.

**Comment by vz3** [comment]
Here's where the notes are at right now

# Breadcrumb research summary

## Overview

We interviewed three users for the last round of usability testing. All test were conducted remotely using InVision Liveshare for video and Hangouts for audio. We interviewed one new cloud.gov user and two existent users.

Our primary focus was to test the most experimental and high profile pattern: the breadcrumb navigation. The navigation was largely a success. We learned of some improvements that could be made, but at no point in any of the tests did users fail to complete a navigation task.

## Universal

- On the breadcrumbs, one user expressed surprise when clicking on the breadcrumb resulted in a dropdown rather than being moved to the point in the experience 
- Little evidence that the Org/Space/App icons are working.

## Overview

- Color bars were not demonstrably successful in communicating org states to users. In the case of critical states, consider a more highly emphasized pattern
- Users did not reference space or app count.
- Did not observe an intentional decision to clicking org name as opposed to clicking in the box to expand. Consider a more clear interaction here between jump to space vs expand accordion.

## Org

- This view was often skipped as users went directly to a space. Should test a task that requires going directly to an org next round.
- Users tripped on distinction between apps and services. Consider A) a different visual style here for services or B) hiding services by default.

## Space

- Functionality of "Add a new services instance" unclear.
