### ISSUE TITLE
Org quick look with space, app count and status on overview page

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#718]
In order for developers to quickly see how their spaces and apps are doing for each org, there should be a list of org quick look UIs on the overview page.

Acceptance criteria:
- [x] There should be a panel with panel rows for each org a user is part of
- [x] Each org quick look row should have space count and app count
- [ ] Each org quick look should show a basic app status, which shows the status of the worst off app (crashed)

Related pattern work: https://github.com/18F/cg-dashboard/issues/722
Dependent on: https://github.com/18F/cg-dashboard/issues/735

**Comment by msecret** [comment]
@suprenant do we have a design for this yet?

**Comment by suprenant** [comment]
@msecret I'm not sure, @thisisdano ?

**Comment by msecret** [comment]
Should be based on design here: https://github.com/18F/cg-dashboard/issues/722

**Comment by msecret** [comment]
### Design: initial request

Only fetch app data for the first 10 or so spaces. Requires new cfApi method to fetch all apps for a space. This should add the apps to the data.

```
function overview() {
  orgActions.fetchAll();
  spaceActions.fetchAll().then((spaces) => {
    const appReqs = spaces.filter((space, i) => i < 11)
      .map((space) => cfApi.fetchSpaceApps(space.guid));
  });
}
```

**Comment by msecret** [comment]
### Design UI

```js
Overview
  Panel
    PanelRow
      OrgQuicklook
        SpaceQuickStats
        AppQuickStats

```

**Comment by suprenant** [comment]
@msecret FYI, we updated the title here and pulled out some details that no longer seemed relevant.

**Comment by msecret** [comment]
### Design: regular data fetching

There's an action to just fetch the app data for a certain space when you click on the space panel to open it up.

```js
app_actions
fetchSpaceApps(spaceGuid) {
  // Maybe we can just use space fetch?
}
```

**Comment by msecret** [comment]
```
Overview
  Panel title="Your organizations"
    PanelGroup
      PanelRow bordered
        OrgQuickLook org, spaces
          PanelGroup
            PanelRow
              SpaceQuickLook space
    
```

**Comment by msecret** [comment]
```js
SpaceQuickLook
  PanelColumn
    AppStatusIcon status{running, crashed, stopped }
  PanelColumn
    
```

**Comment by msecret** [comment]
When an org quicklook doesn't have the app data (because we didn't fetch it) then we'll just show a black icon and no status bar. We can always show the amount of apps number.

**Comment by msecret** [comment]
We might want to separate out the functionality for the complex status bar icon on the org quicklook. Seems somewhat complicated to design.

```
OrgQuickStatus spaces, apps?
```

**Comment by msecret** [comment]
I had a question about this as I start implementing it. @thisisdano @suprenant .

What do we want to do with the content that's currently on the [overview page](https://dashboard.cloud.gov/#/dashboard)? It includes useful information such as switching to `fr` url if on govcloud, what the dashboard is, getting an empty sandbox, and the issue tracker. @brittag originally wrote this content, maybe she has some opinions on what should happen to it?

**Comment by brittag** [comment]
Oh hmm, thanks for tagging me! I'm not sure what the overall future homepage design is meant to look like right now, but opinions about the homepage:

1. The GovCloud dashboard note is probably important to keep for now in some way, until we have a better way to direct people to the right spot (or until we shut down E/W).
2. I'd really like the dashboard to have some way of telling people where to find the source code and issue tracker (it could be a footer of some kind).
3. I believe it's helpful for the homepage to communicate to people what the dashboard can _do_ for them (and how it's different from the CLI), although that doesn't have to look like the copy I wrote.

**Comment by msecret** [comment]
Here's what it looks like https://github.com/18F/cg-dashboard/issues/722#issuecomment-262308896

**Comment by brittag** [comment]
Oh cool! There could probably be a bit of copy at the top somewhere to explain what the dashboard can do, put the GovCloud note in some sort of "notice" box, and find somewhere in the footer for the source code link.

**Comment by brittag** [comment]
(I don't have a strong opinion right now about how the explaining-the-dashboard part should happen - I just suspect there's a user need here along the lines of "ok, cloud.gov is giving me both a CLI and a dashboard - how are they different? what does this dashboard give me?")

**Comment by thisisdano** [comment]
First thoughts here:

- the ex/govcloud/fr thing is a big dumb complication, and we need to address it right at the top of the page, like in some kind message panel. in the best of possible worlds this messaging is also part of the signin flow, but  :( for now
- Some of that content could be repackaged a bit into what I think of as "New User Content" (see the [invision](https://gsa.invisionapp.com/share/838UY596S#/192771128_Usage-And-Limits--default)) for some "here are some things to do on the dashboard" kind of stuff
- I also think that what-do-i-do-next prompts can and should be handled with helpful empty states
- "what's the difference between the CLI and the dashboard" should probably be a page in the docs, maybe linked from the New User Content
- Also getting thoughts about a footer together in that  [invision](https://gsa.invisionapp.com/share/838UY596S#/192771128_Usage-And-Limits--default). It feels like it could include
  - link to marketing home (cloud.gov/home)
  - link to github information (contributing)
  - Any other footer-style info; info about open-source, public domain, etc. 
  - Contact, since we don't really have an explicit Help section (yet)

Definitely a goal of this (and all other) pages should be to clearly communicate what can be done. I think copy about what the dashboard can do is the kind of thing that should be partly communicated through explicit text and partly through design. And I feel that this copy is less a big block of heres-what-you-can-do text (though that _could_ and exist in docs — some kind of Dashboard documentation should exist!) and more guiding you to next steps at the appropriate time.

I'll try to work through more examples of how this could work — and give a pass at how the New User section might look, too. Stay tuned.

**Comment by msecret** [comment]
@thisisdano this overview page is getting close to complete and ready for launch. Should we hold off on launching it until we made sure we put some of this information back in it?

**Comment by msecret** [comment]
Ok. We'll have to make this configurable, as AUS didn't want this content.

**Comment by thisisdano** [comment]
For now I would disregard this AUS needs, as this content and its presentation will change considerably at some point. I don't think they know if they want it yet cos we don't even know what it will be.

**Comment by thisisdano** [comment]
In other words, I wouldn't let it hold up getting this out the door

**Comment by thisisdano** [comment]
@msecret 
A few things things about the overview page org card display:

1. The `orgName` link should link to the org itself, not open the card. (With the current behavior, there's no link to the org...)
2. Clicking anywhere in the card that isn't an explicit link should open/close the card.
3. Users with <= 5 orgs should default to open view.

**Comment by msecret** [comment]
For "Users with <= 5 orgs should default to open view.", I'm not sure this is a good idea if we're putting the cheatsheet content at the bottom.

**Comment by suprenant** [comment]
This looks good, but I'm not sure how to test this criterion: 
 - Each org quick look should show a basic app status, which shows the status of the worst off app (crashed)

@adborden can you possibly help here?

**Comment by msecret** [comment]
In reality, we need fake data to test this, so we can see what it looks like when theres a crashed app. But you can also check that the status is green when all apps are running under a space or black when some are running and some are not.

**Comment by adborden** [comment]
I set up the scenario [here](https://dashboard-staging.apps.cloud.gov/#/org/48b3f8a1-ffe7-4aa8-8e85-94768d6bd250/spaces/82af0edb-8540-4064-82f2-d74df612b794) and there's definitely an [issue with crashed apps](https://github.com/18F/cg-dashboard/issues/860), but I would still expect the bar indicator to be black for the stopped app, since that's the worse one, right?

![screenshot from 2016-12-22 14-21-38](https://cloud.githubusercontent.com/assets/509703/21442333/2c9de6e2-c852-11e6-9984-66b6d9348c16.png)

**Comment by adborden** [comment]
Looks good now
