### ISSUE TITLE
Implement icons for org overview

### ISSUE THREAD

**Issue by msecret** [18F/cg-dashboard#767]
In order for a developer to visual separate different components such as orgs, spaces and apps on the overview page, there should be icons that express different information.

Design: https://github.com/18F/cg-dashboard/issues/722

Acceptance criteria:
- [x] Icons are displayed as is in the design
- [x] App icons change color based on status

**Comment by msecret** [comment]
@thisisdano what's the best way to get these icons? Export from sketch?

**Comment by suprenant** [comment]
@adborden could you help verify this item? Past testing that, this looks good to me:
 - App icons change color based on status

**Comment by adborden** [comment]
You can see in this screenshot the icons change color based on state. But I opened [this bug](https://github.com/18F/cg-dashboard/issues/860) about the crashed state, since I expect one of these to be orange.

![screenshot from 2016-12-22 14-17-39](https://cloud.githubusercontent.com/assets/509703/21442255/9324ccec-c851-11e6-9563-d0e7d87cb692.png)
