### ISSUE TITLE
Implement breadcrumb design

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#813]
As a cloud.gov user, I'd like to be able to navigate to another org, space, or app, depending upon where I am.

Design:
18F/cg-design#24
https://gsa.invisionapp.com/d/main#/console/8652272/208123072/preview

Ref: https://github.com/18F/cg-dashboard/issues/716

Note:
 - The current Invision designs contain additional elements/levels of fidelity that we do not plan to implement as part of this issue but may possibly pick up as follow-on work later.

Noted from mid-sprint review discussion:
 - Display all orgs/spaces/apps when these are clicked
 - May fine-tune interaction details, but design mostly there

Acceptance criteria:
- [ ] Org, space and app views have the breadcrumb design implemented
- [ ] At the org level, I am able to move to another org
- [ ] At the space level, I am able to move to another space (with the same org) or another org
- [ ] At the app level, I am able to move to another org, space (within selected org), or app (within selected space)

**Comment by suprenant** [comment]
@vz3 to groom this further

**Comment by adborden** [comment]
There is an existing branch for the prototype [adborden/breadcrumb-nav](https://github.com/18F/cg-dashboard/compare/adborden/breadcrumb-nav) which might be useful to reference for the implementation.

Some notes...

## Styles

Styles for the prototype already exist in cg-style master in [nav-breadcrumb.scss](https://github.com/18F/cg-style/blob/master/src/css/components/nav-breadcrumb.scss).

## Router

I was quick to just pull the router reference from `main.js`, but might spend a little more time on it in the next go-around. Because routes are not handled by actions, there is some friction here. You'll notice that when moving "up" in the hierarchy, like from an app to a space, we need to manually reset the state by clearing the current app.

## Sidenav

The prototype assumed the sidenav would be removed, so the code handling the toggle of the sidenav menus was dropped when it conflicted with things. Since we cannot drop the sidenav yet, we'll have to make sure the menu toggle actions are cleanly separated. Unfortunately, I don't remember what some of the issues were here.

**Comment by thisisdano** [comment]
I'm gonna try and prototype this up in the Pattern Library. 
Goal is to get something to see by EOD 12/19.

It'll be contingent on https://github.com/18F/cg-style/pull/225 so hopefully we can get this merged as soon as possible

**Comment by thisisdano** [comment]
OK, took a swing at this here: https://github.com/18F/cg-style/pull/228

It's a pretty complicated pattern and took a while! I built it entirely in utility classes to avoid adding/influencing any existing styles. It should be relatively simple to rebuild it in the typical css/stylesheet manner if desired. I made it with `div`s and `span`s — it could benefit from a more semantic use of elements.

There's probably also a bit of work involved in making the pattern as accessible as possible from a code / screen reader perspective — I have some ideas. 

![screen shot 2016-12-19 at 9 51 35 pm](https://cloud.githubusercontent.com/assets/11464021/21339701/23c0ce54-c636-11e6-9d42-3df261eda392.png)

- - -

![screen shot 2016-12-19 at 9 51 14 pm](https://cloud.githubusercontent.com/assets/11464021/21339705/290b1b26-c636-11e6-8486-0305d4ec6c9a.png)

- - -

![screen shot 2016-12-19 at 9 51 52 pm](https://cloud.githubusercontent.com/assets/11464021/21339708/2bb0df3c-c636-11e6-8d76-ba99937b5486.png)

- - -

![screen shot 2016-12-19 at 9 51 44 pm](https://cloud.githubusercontent.com/assets/11464021/21339710/2de89e8e-c636-11e6-8aee-8f3e70c89b48.png)
