### ISSUE TITLE
Modify metadata of current services

### ISSUE THREAD

**Issue by msecret** [18F/cg-dashboard#857]
In order for manager to see clear information about available services and what they do, the metadata for the services should be edited and made consistent.

Notes: 
 - Guidelines around metadata could be useful
 - Documentation around adding new services/metadata would be useful

Acceptance criteria
- [ ] The documentation on services should match up with the names changed for the services, https://cloud.gov/docs/services/.

Here's where all the data can be found:
- RDS: https://github.com/18F/aws-broker, this is probably deprecated: https://github.com/dlapiduz/rds-broker
- Elasticswarm: [k8 broker 17](https://github.com/18F/kubernetes-broker/tree/master/catalogData/elasticsearch17), [k8 broker 23](https://github.com/18F/kubernetes-broker/tree/master/catalogData/elasticsearch23), [k8 broker 24](https://github.com/18F/kubernetes-broker/tree/master/catalogData/elasticsearch24)
- Redis: [k8 broker](https://github.com/18F/kubernetes-broker/tree/master/catalogData/redis28)
- S3: https://github.com/cloudfoundry-community/s3-cf-service-broker
- aws-rds: same as RDS
- CDN route: https://github.com/18F/cf-cdn-service-broker

**Comment by msecret** [comment]
### Mapping
![pasted image at 2016_12_21 03_14 pm](https://cloud.githubusercontent.com/assets/1701077/21442809/45f131e6-c855-11e6-809e-2917412e4c38.png)

**Comment by msecret** [comment]
Here are the PRs to make this happen:

- https://github.com/18F/kubernetes-broker/pull/35
- https://github.com/18F/aws-broker/pull/26
- https://github.com/18F/cf-cdn-service-broker/pull/56

**Comment by msecret** [comment]
@thisisdano @vz3 it would help if you guys could look at the above PRs quickly to check that the data updates are correct.

**Comment by thisisdano** [comment]
Left comments on those PR (or approved if no comments)

**Comment by msecret** [comment]
All PRs have been merged, I'm unsure of when they will be deployed

**Comment by suprenant** [comment]
Noting that we'll need Atlas to make these deployments.

**Comment by suprenant** [comment]
@msecret – @LinuxBozo mentioned here again that the PRs have been merged. Can you say if we are seeing them deployed? https://gsa-tts.slack.com/archives/cloud-gov-atlas/p1483731559003539

**Comment by msecret** [comment]
You can check on the marketplace page in dashboard, I don't see it up to date yet.

**Comment by LinuxBozo** [comment]
There were a few hiccups in the deployment pipelines that should now be resolved. You should see these changes on the govcloud side of things.

**Comment by adborden** [comment]
This is looking good, with one exception: I'm not seeing the `cdn-route` [changes](https://github.com/18F/cf-cdn-service-broker/pull/56/files). @LinuxBozo is it possible that the `cdn-route` hasn't been deployed yet?

**Comment by adborden** [comment]
ping @LinuxBozo

**Comment by adborden** [comment]
Looking good :)

**Comment by brittag** [comment]
YAY for progress! Looks like the descriptions (as seen in the dashboard) aren't yet consistent with the descriptions at https://cloud.gov/docs/services/ and on each service sub-page - I see this is an AC here, so I'll reopen this issue.

Also, it looks like some of these descriptions have periods at the end and some don't - I'd suggest adding periods to all of them for consistency, since some are sentence fragments and some are sentences.

![screen shot 2017-02-01 at 6 46 32 pm](https://cloud.githubusercontent.com/assets/391313/22535281/e0064306-e8ae-11e6-902d-35836a36dcc5.png)

It looks like my followup edits at https://github.com/18F/cg-deploy-s3-broker/pull/9 and https://github.com/18F/aws-broker/pull/27 didn't make it in - but maybe better for you all to follow up on those than me, since maybe you want to make additional edits or replace those PRs with other PRs.

**Comment by adborden** [comment]
We can't really update the descriptions for `cloud-gov-service-provider` or `cloud-gov-identity-provider` as they are hard-coded https://github.com/cloudfoundry-community/uaa-credentials-broker/issues/20
