### ISSUE TITLE
Make marketplace easier to find

### ISSUE THREAD

**Issue by suprenant** [18F/cg-dashboard#974]
We might have designs for this already, but some users have reported that the Marketplace can be difficult to find, so we should review this and propose an updated design.

From @brittag:
_I was just trying to get back to that and temporarily couldn't remember how to find the marketplace_
_it may make sense to put in something as simple as a little table of contents at the top of the space page for space overview, space users, service instances, marketplace_

**Comment by adborden** [comment]
We used to link to the marketplace in different contexts, however we currently are lacking the ability to link with fragments (`#fragment`) so there is no way to [link directly the marketplace anymore](https://github.com/18F/cg-dashboard/issues/896). I suspect this is part of the problem.

**Comment by brittag** [comment]
For future reference - this came up today when [@mogul - Bret Mogilefsky] and I were observing a new user learn how to use cloud.gov - while explaining cloud.gov services to them, we stumbled a bit when trying to explain where to find the marketplace in the dashboard.

I realized from this observation that a new user likely doesn't yet know that a service marketplace should exist, so they don't even know that they should be looking for it. If it's buried a bit, they may not find it, and if they hear about it and look for it, they likely wouldn't guess to look for it on a space page (since they don't yet have the mental model that service instances are created as available in a space and then bound to an app).

**Comment by mogul** [comment]
I noted also that when you create a service instance in a given space, there's no help for finding your way back to that space... You have to know to go back to the org, space, and app before binding the new service instance.

**Comment by brittag** [comment]
Notes from that overall user research session, for context: https://docs.google.com/document/d/1ojdaQ74pvlAt_7UQwXsKJvgSQ_g90mwS7Krs3KK_m8Q/edit

**Comment by adborden** [comment]
cc @msecret 

Great info here, thank you! We were just talking about prioritizing usability tests around "new user experience" for next sprint which would include docs and the dashboard.

**Comment by suprenant** [comment]
Echoing this need, I've been having a hard time finding this.
